### ISSUE TITLE
feat: reload argument for serve cli command

### ISSUE THREAD

**Issue by ishafiul** [dartarcade/arcade#24]
It would be great to have two separate CLI commands for `arcade_cli` to serve the server. I have very little knowledge about Dart HTTP deployment, almost none actually. However, from my perspective, having this feature would be very beneficial. With the `--watch` flag, during development I can monitor file changes and run build_runner concurrently. Then, when I need to deploy, I can quickly start the server by using the `serve` command. Of course, arcade_cli would need to be installed globally to use this feature when we can run the file from the `bin` folder instead of using an extra CLI library.

**Comment by exaby73** [comment]
As discussed, the ideal way is to compile the Dart server to a binary using `dart compile exe`. A convenience command could be added, something like `arcade build`, to do this from the CLI. `arcade serve` is meant to be a dev server only and therefore watches files by default. Due to these reasoning, I'll close this issue
